[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.153", features = ["derive"] }
reqwest = { version = "0.11.14", features = ["blocking", "json"] }
